### ISSUE TITLE
Resource allocation groups under role name instead of resource

### ISSUE THREAD

**Issue by TinHoangVu** [Puzzlepart/prosjektportalen365#916] opened 2022-12-06 16:13 UTC
**Describe the bug**

The resource allocation view in portfolio does not group properly. When u allocate the resource to a project and give him a role, it will  group under the role name, instead of the resource. Does not happen to all the elements.

**To Reproduce**

1. Go to 'Sentrale ressursallokeringslista' and allocate a resource.
2. Go to a project and allocate the same resource to the project with a role. 
4. See that the project element does not group under the name of the resource.  

**Expected behavior**

The resource allocation elements should group under the name of the resource, and not the role when name is not empty.

**About your setup**

- Google chrome
- Installed version: 1.7.2

**Comment by olemp** [comment] 2022-12-13 08:51
Cannot reproduce this @TinHoangVu.

![image](https://user-images.githubusercontent.com/7606007/207270495-db83f12e-9eb3-4477-9663-07a922e1a9fc.png)


![image](https://user-images.githubusercontent.com/7606007/207270421-8ec7d1fe-2376-4fdb-8b27-b2f385ed3215.png)

**Comment by tarjeieo** [comment] 2022-12-15 20:03
I cannot reproduce for new entries either, but I'm seeing an instance of this in our PP environment. Guessing an issue with some data missing from search. Not a priority for 1.8 IMO, unless we hear/see this from others.
![image](https://user-images.githubusercontent.com/1837390/207956028-41432104-8d5a-4768-9ff2-6c0a1c1f0ae2.png)

**Comment by tarjeieo** [comment] 2022-12-23 10:59
Fixed in #931 and will be part of next release

**Closed by tarjeieo** 2022-12-23 10:59 UTC
Labels: bug
