### ISSUE TITLE
Guests are not able to load projects from the webpart(projectlist) at the portfolio

### ISSUE THREAD

**Issue by joachimgje** [Puzzlepart/prosjektportalen365#898] opened 2022-11-22 09:01 UTC
We are experiencing this on multiple installations on different tenants.

![image](https://user-images.githubusercontent.com/22074910/203269153-96dcdf6b-1a9e-42ae-a9ce-49baca227ce7.png)
![image](https://user-images.githubusercontent.com/22074910/203269267-8b226a5d-c3db-4c46-9feb-11e5815b4a83.png)

**Comment by pzljanb** [comment] 2022-11-23 07:51
This is working on some installations/ tenants. The problem is only related to this one webpart on the Home page.
Porteføljeoversikt in addition to all other webparts is working as expected.

**Comment by olemp** [comment] 2022-12-20 10:58
This is fixed in https://github.com/Puzzlepart/prosjektportalen365/commit/2ec60739e352fea2ad08cea5a56cf56581257afd (FYI @tarjeieo)

**Closed by olemp** 2022-12-20 10:58 UTC
Labels: bug
