### ISSUE TITLE
Support for /teams as managed path

### ISSUE THREAD

**Issue by pzlespen** [Puzzlepart/prosjektportalen365#177] opened 2019-12-18 09:10 UTC
**Describe the bug**
When trying to install Prosjektportalen 365 on a Site Collection that uses /teams instead of /sites as managed path, the script stops. (Line 91 of Install.ps1 in version 1.1.6).

**Comment by olemp** [comment] 2019-12-18 09:24
There was some issues that made us disable install for other sites than sites with managed path `sites/`. 

Is it really important to be able to install to /teams/xxxx?

**Comment by olemp** [comment] 2019-12-18 09:24
So it's not a bug, it's by-design.

**Comment by pzlespen** [comment] 2019-12-18 09:26
It is important to have it, since it is supported, and we have customers using it. Bug I can agree that it is not a bug, but a feature we should add in the next version instead. Bypassed it by modifying the mentiond line in Install.ps1.

**Comment by olemp** [comment] 2019-12-18 09:31
Will be included in next patch version.

**Closed by olemp** 2019-12-18 09:31 UTC
Labels: bug
