### ISSUE TITLE
In Project status, risks are not showing historical data when browsing older satus reports

### ISSUE THREAD

**Issue by pzlespen** [Puzzlepart/prosjektportalen365#525] opened 2021-09-16 05:32 UTC
**Describe the bug**
In Project status, risks are not showing historical data when browsing older satus reports.

**Expected behavior**
When you look at an old status report, all elements should show the data from that time.

**Comment by tarjeieo** [comment] 2021-09-20 10:03
This is a duplicate of https://github.com/Puzzlepart/prosjektportalen365/issues/374

**Closed by tarjeieo** 2021-09-20 10:03 UTC
Labels: bug
