### ISSUE TITLE
Resource allocation displays 0% no matter the input

### ISSUE THREAD

**Issue by Rundez** [Puzzlepart/prosjektportalen365#610] opened 2021-12-16 08:52 UTC
**Describe the bug**
Posting this on behalf of @danielwiese

The resource allocation module at portfolio level displays that the load is 0% with no exception. This happens to the dialog as well as the timeline elements. (see screenshots below) 

**To Reproduce**

1. Go to "Ressursoversikt"
2. Make sure that there is elements in the central resource allocation list
3. Watch the 0% load appear

**Screenshots**
![image](https://user-images.githubusercontent.com/38385042/146338632-8d9bb8c2-aadc-4272-8d0b-e6d558130605.png)
![image](https://user-images.githubusercontent.com/38385042/146338699-88887ea9-e8ee-408b-9635-43973f4c6425.png)
![image](https://user-images.githubusercontent.com/38385042/146338734-2d3ff1c9-78f6-4b26-b2a9-324e8c0d9b0f.png)

**Comment by tarjeieo** [comment] 2022-01-26 21:29
Hard to do anything with this one, as the value reported back from search is actually zero. Not closing just yet, but unsure on what action to take

**Comment by danielwiese** [comment] 2022-03-24 17:48
Any updates on this issue?

**Comment by tarjeieo** [comment] 2022-05-12 20:21
Finally found the culprit with this one. The problem is that in the project template, there is a field declaration on the list itself (https://github.com/Puzzlepart/prosjektportalen365/blob/521ccf5775d2c00e55b2844c13d4ca7bab07e2bb/Templates/JsonTemplates/_JsonTemplateProject.json#L1251). In this commit (https://github.com/Puzzlepart/prosjektportalen365/commit/77d60e940097933b047372524362f4c4d4904e75) we implemented "field descriptions" to better indicate what the field does and is used for. However, what happened here is that the field went from being a site column to being a list column - which SharePoint search does not create a managed property for - yielding zero values in the GtResourceLoadOWSNMBR managed property.

To fix this we need to
1. Stop using list field declarations in the template(s)
2. Create a script that iterates all projects, saves the current value for all resource allocation items, deletes the column, adds the column back from site columns, and finally restores the previous value.

**Comment by tarjeieo** [comment] 2022-05-23 11:34
This issue is resolved in #710 and will be part of the next release

**Closed by tarjeieo** 2022-05-23 11:34 UTC
Labels: bug, priority: high

**Comment by danielwiese** [comment] 2022-05-23 11:36
Yes, gr8 work @tarjeieo  <3
