### ISSUE TITLE
Handling of unpublished reports should be improved

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#295] opened 2020-08-13 06:18 UTC
Handling of unpublished reports should be improved.

**Proposal:**
Disable the button 'Ny statusrapport' When there is an unpublished report in place.

**Goal:**
To only have Published reports (plus one unpublished/ current report)

_Originally posted by @pzljanb in https://github.com/Puzzlepart/prosjektportalen365/issues/121#issuecomment-672831014_

**Comment by Remi749** [comment] 2020-09-17 11:18
Fixed in commit: https://github.com/Puzzlepart/prosjektportalen365/commit/a64735435f1c2f4318a820b5657ddc608f84aa15

What this commit does:
- Disable the button "Ny statusrapport" when a report is unpublished

How to test:
1. Create a new report.
2. The button "Ny statusrapport" will stay disabled until you publish the report.

**Comment by Remi749** [comment] 2020-09-17 13:18
@olemp since the commit to branch failed, can you confirm this commit to the dev so I can close the issue.

**Comment by Remi749** [comment] 2020-09-18 08:42
here is the commit if you didn't find it: https://github.com/Puzzlepart/prosjektportalen365/commit/a64735435f1c2f4318a820b5657ddc608f84aa15

**Comment by olemp** [comment] 2020-09-18 08:43
> here is the commit if you didn't find it: [a647354](https://github.com/Puzzlepart/prosjektportalen365/commit/a64735435f1c2f4318a820b5657ddc608f84aa15)

Seems like the commit is in the `dev` branch already?

**Comment by Remi749** [comment] 2020-09-18 08:44
Yes.

**Comment by olemp** [comment] 2020-09-18 08:48
https://github.com/Puzzlepart/prosjektportalen365/commit/a64735435f1c2f4318a820b5657ddc608f84aa15 only disables the new report command if **the current** report is not published. Seems like this doesn't cover this issue @Remi749

**Comment by olemp** [comment] 2020-09-18 08:49
> [a647354](https://github.com/Puzzlepart/prosjektportalen365/commit/a64735435f1c2f4318a820b5657ddc608f84aa15) only disables the new report command if **the current** report is not published. Seems like this doesn't cover this issue @Remi749

@pzljanb originally posted this btw. He knows how he wants it 🚀

**Comment by Remi749** [comment] 2020-09-18 08:53
As descibed in the proposal, the commit disables the button when there is a unpublished report in place

The goal is also fulfilled as the there is only on unpublished/current report possible, therefore only published reports.

Have I misunderstood this?

**Comment by olemp** [comment] 2020-09-18 08:56
> As descibed in the proposal, the commit disables the button when there is a unpublished report in place
> 
> The goal is also fulfilled as the there is only on unpublished/current report possible, therefore only published reports.
> 
> Have I misunderstood this?

The commit disables the command when:

`selectedReport.moderationStatus !== strings.GtModerationStatus_Choice_Published`.

I might misunderstand something like, let me check it out after lunch.

**Comment by pzljanb** [comment] 2020-09-18 08:59
As long as you cant start a new report if there already is a unpublished report inplace (as the latest report) the problem is solved.

BUT, if you select an older published report and by this can create a new report (even if the latest one is unpublished), we still have issue.
________________________________
Fra: Bloom <notifications@github.com>
Sendt: fredag 18. september 2020 10:54
Til: Puzzlepart/prosjektportalen365 <prosjektportalen365@noreply.github.com>
Kopi: Jan Lindset <jan.lindset@puzzlepart.com>; Mention <mention@noreply.github.com>
Emne: Re: [Puzzlepart/prosjektportalen365] Handling of unpublished reports should be improved (#295)


As descibed in the proposal, the commit disables the button when there is a unpublished report in place

The goal is also fulfilled as the there is only on unpublished/current report possible, therefore only published reports.

Have I misunderstood this?

**Comment by Remi749** [comment] 2020-09-18 09:54
@pzljanb, 

> BUT, if you select an older published report and by this can create a new report (even if the latest one is unpublished), we still have issue."

As of right now this is still an issue, this was no taken into consideration for this issue, but I will look into it right away.


> As long as you cant start a new report if there already is a unpublished report inplace (as the latest report) the problem is solved.

This works as your describe.

**Comment by Remi749** [comment] 2020-09-18 11:35
Fixed in new PR #309

**Closed** 2020-09-18 12:03 UTC
Labels: Complexity: small, Priority: medium, easy-task, enhancement, frontend
