### ISSUE TITLE
Loading timeline for Program results in error regarding replace from shared package - hubsiteId

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen365#936] opened 2022-12-27 20:05 UTC
**Describe the bug**

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/28678468/209716904-ffb8fa89-1261-4f7e-9222-1073a8058778.png">

The hubSiteId returns undefined when trying to setup configuration during loading of timeline webpart. The new rework of the sp-hubsite-service fails and needs to be fixed for ProgramWebParts. See error below and steps to reproduce. I have checked and hubSiteId is null. 

<img width="622" alt="image" src="https://user-images.githubusercontent.com/28678468/209716657-fb61a8b8-8522-43f8-a96a-f246f556989e.png">

**To Reproduce**

1. Go to a Program running latest from dev
2. Click on "Tidslinje" under "Programinnhold"
3. Witness bug

**Expected behavior**
Webpart should load like before.

**Comment by tarjeieo** [comment] 2023-01-02 22:30
The problem is not related to the hubsite-rewrite, it's related to that the timeline web part is using the wrong implementation of fetchProjectTimelineData (https://vscode.dev/github/Puzzlepart/prosjektportalen365/blob/984dba785f0e33a7790daa22c24efba61e34a060/SharePointFramework/PortfolioWebParts/src/components/ProjectTimeline/useProjectTimelineDataFetch.ts#L142).

When debugging, it looks like it's using the "not in use" fetchProjectTimelineData of the program-package (https://vscode.dev/github/Puzzlepart/prosjektportalen365/blob/984dba785f0e33a7790daa22c24efba61e34a060/SharePointFramework/ProgramWebParts/src/data/index.ts#L331). This leads to the promise-error we're seeing in console, and subsequent failures in the code.

Need to look into this together @Remi749

**Comment by tarjeieo** [comment] 2023-01-03 18:44
Resolved in #937

**Closed** 2023-01-03 18:44 UTC
Labels: bug, priority: high, complexity: medium
